---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letschat-pvc
  labels:
    appname: letschat
    placement: letschat-placement-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi