apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/bitnami/mongodb:5.0
      generation: null
      importPolicy: {}
      name: "5.0"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
